module compilacaoIDL{

	struct Jogador {

		string nome;
		long lugar;
		long quantidadePalitosRestantes;
		long quantidadePalitosApostados;
		long palpite;
		boolean apostou;
		boolean palpitou;
	};

    interface Cliente {

	    void sentar(in string nome, in long lugar);
	    void escreverMensagem(in string mensagem);
	    void apostar(in long lugar);
	    void palpite(in long lugar, in long palpite);
	    void reiniciarRodada(in long lugar, in long quantidadePalitosRestantes);
	    void sairSala(in long lugar);
    };

	interface Servidor {

	    Jogador getJogador(in string nome);
	    void adicionarJogador(in string nome);
        void removerJogador(in string nome);
	    boolean verificarNomeJogador(in string nome);
	    boolean verificarLugar(in string nome, in long lugar);
	    void atualizarLugares();
		void enviarMensagem(in string nome, in string mensagem);
		void adicionarPalito(in string nome);
		void removerPalito(in string nome);
		void apostar(in string nome);
		boolean verificarPalpitar(in string nome);
		boolean palpitar(in string nome, in long palpite);
	};



};