module compilacaoIDL{

	struct Jogador {
		string nome;
		long lugar;
		long totalPalitos;
		long quantidadePalitosApostados;
	};

	typedef sequence<Jogador> ListaJogadores;

	interface Servidor {
	    ListaJogadores getJogadores();
	    boolean verificarNomeJogador(in string nome);
	    boolean verificarLugar(in Jogador jogador, in long lugar);
		void atualizarChat(in Jogador jogador, in string mensagem);
		void passarTurno(in Jogador jogador);
        void vencedor(in Jogador jogador);
        void perdedor(in Jogador jogador);
		void adicionarJogador(in Jogador jogador);
        void removerJogador(in Jogador jogador);
	};

	interface Eventos {
	    void sentar(in long lugar);
	    void enviarMensagem(in string mensagem);
	    void esolherQuantidadePalitos(in Jogador jogador, in long quantidadePalitos);
	    void apostar(in Jogador jogador, in long quantidadePalitos);
	    void entrarPartida(in Jogador jogador);
        void sair(in long lugar);
   };

};