package compilacaoIDL;


/**
* compilacaoIDL/_AcoesJogadorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Wednesday, June 14, 2017 4:58:16 PM GMT-03:00
*/

public class _AcoesJogadorStub extends org.omg.CORBA.portable.ObjectImpl implements compilacaoIDL.AcoesJogador
{

  public void enviarMensagem (String mensagem)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enviarMensagem", true);
                $out.write_string (mensagem);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enviarMensagem (mensagem        );
            } finally {
                _releaseReply ($in);
            }
  } // enviarMensagem

  public void esolherQuantidadePalitos (compilacaoIDL.Jogador jogador, int quantidadePalitos)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("esolherQuantidadePalitos", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $out.write_long (quantidadePalitos);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                esolherQuantidadePalitos (jogador, quantidadePalitos        );
            } finally {
                _releaseReply ($in);
            }
  } // esolherQuantidadePalitos

  public void apostar (compilacaoIDL.Jogador jogador, int quantidadePalitos)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("apostar", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $out.write_long (quantidadePalitos);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                apostar (jogador, quantidadePalitos        );
            } finally {
                _releaseReply ($in);
            }
  } // apostar

  public void entrarPartida (compilacaoIDL.Jogador jogador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("entrarPartida", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                entrarPartida (jogador        );
            } finally {
                _releaseReply ($in);
            }
  } // entrarPartida

  public void sairPartida (compilacaoIDL.Jogador jogador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sairPartida", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sairPartida (jogador        );
            } finally {
                _releaseReply ($in);
            }
  } // sairPartida

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:compilacaoIDL/AcoesJogador:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AcoesJogadorStub
