package compilacaoIDL;


/**
* compilacaoIDL/_ServidorStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Thursday, June 15, 2017 6:49:05 PM GMT-03:00
*/

public class _ServidorStub extends org.omg.CORBA.portable.ObjectImpl implements compilacaoIDL.Servidor
{

  public compilacaoIDL.Jogador[] getJogadores ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getJogadores", true);
                $in = _invoke ($out);
                compilacaoIDL.Jogador $result[] = compilacaoIDL.ListaJogadoresHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getJogadores (        );
            } finally {
                _releaseReply ($in);
            }
  } // getJogadores

  public boolean verificarNomeJogador (String nome)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("verificarNomeJogador", true);
                $out.write_string (nome);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return verificarNomeJogador (nome        );
            } finally {
                _releaseReply ($in);
            }
  } // verificarNomeJogador

  public boolean verificarLugar (compilacaoIDL.Jogador jogador, int lugar)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("verificarLugar", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $out.write_long (lugar);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return verificarLugar (jogador, lugar        );
            } finally {
                _releaseReply ($in);
            }
  } // verificarLugar

  public void atualizarChat (compilacaoIDL.Jogador jogador, String mensagem)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("atualizarChat", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $out.write_string (mensagem);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                atualizarChat (jogador, mensagem        );
            } finally {
                _releaseReply ($in);
            }
  } // atualizarChat

  public void passarTurno (compilacaoIDL.Jogador jogador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("passarTurno", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                passarTurno (jogador        );
            } finally {
                _releaseReply ($in);
            }
  } // passarTurno

  public void vencedor (compilacaoIDL.Jogador jogador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("vencedor", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                vencedor (jogador        );
            } finally {
                _releaseReply ($in);
            }
  } // vencedor

  public void perdedor (compilacaoIDL.Jogador jogador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("perdedor", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                perdedor (jogador        );
            } finally {
                _releaseReply ($in);
            }
  } // perdedor

  public void adicionarJogador (compilacaoIDL.Jogador jogador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adicionarJogador", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                adicionarJogador (jogador        );
            } finally {
                _releaseReply ($in);
            }
  } // adicionarJogador

  public void removerJogador (compilacaoIDL.Jogador jogador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removerJogador", true);
                compilacaoIDL.JogadorHelper.write ($out, jogador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removerJogador (jogador        );
            } finally {
                _releaseReply ($in);
            }
  } // removerJogador

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:compilacaoIDL/Servidor:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServidorStub
