package compilacaoIDL;


/**
* compilacaoIDL/AcoesJogador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Tuesday, June 13, 2017 8:59:52 PM GMT-03:00
*/

public interface AcoesJogador extends AcoesJogadorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AcoesJogador
