package compilacaoIDL;


/**
* compilacaoIDL/AcoesJogadorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Wednesday, June 14, 2017 4:58:16 PM GMT-03:00
*/

abstract public class AcoesJogadorHelper
{
  private static String  _id = "IDL:compilacaoIDL/AcoesJogador:1.0";

  public static void insert (org.omg.CORBA.Any a, compilacaoIDL.AcoesJogador that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static compilacaoIDL.AcoesJogador extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (compilacaoIDL.AcoesJogadorHelper.id (), "AcoesJogador");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static compilacaoIDL.AcoesJogador read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AcoesJogadorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, compilacaoIDL.AcoesJogador value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static compilacaoIDL.AcoesJogador narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof compilacaoIDL.AcoesJogador)
      return (compilacaoIDL.AcoesJogador)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      compilacaoIDL._AcoesJogadorStub stub = new compilacaoIDL._AcoesJogadorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static compilacaoIDL.AcoesJogador unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof compilacaoIDL.AcoesJogador)
      return (compilacaoIDL.AcoesJogador)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      compilacaoIDL._AcoesJogadorStub stub = new compilacaoIDL._AcoesJogadorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
