package compilacaoIDL;

/**
* compilacaoIDL/AcoesJogadorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Tuesday, June 13, 2017 8:59:52 PM GMT-03:00
*/

public final class AcoesJogadorHolder implements org.omg.CORBA.portable.Streamable
{
  public compilacaoIDL.AcoesJogador value = null;

  public AcoesJogadorHolder ()
  {
  }

  public AcoesJogadorHolder (compilacaoIDL.AcoesJogador initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = compilacaoIDL.AcoesJogadorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    compilacaoIDL.AcoesJogadorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return compilacaoIDL.AcoesJogadorHelper.type ();
  }

}
