package compilacaoIDL;


/**
* compilacaoIDL/AcoesJogadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Wednesday, June 14, 2017 4:58:16 PM GMT-03:00
*/

public interface AcoesJogadorOperations 
{
  void enviarMensagem (String mensagem);
  void esolherQuantidadePalitos (compilacaoIDL.Jogador jogador, int quantidadePalitos);
  void apostar (compilacaoIDL.Jogador jogador, int quantidadePalitos);
  void entrarPartida (compilacaoIDL.Jogador jogador);
  void sairPartida (compilacaoIDL.Jogador jogador);
} // interface AcoesJogadorOperations
