package compilacaoIDL;


/**
* compilacaoIDL/AcoesJogadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Tuesday, June 13, 2017 8:59:52 PM GMT-03:00
*/

public interface AcoesJogadorOperations 
{
  void enviarMensagem (compilacaoIDL.Jogador jogador, String texto);
  void esolherQuantidadePalitos (compilacaoIDL.Jogador jogador, int quantidadePalitos);
  void apostar (compilacaoIDL.Jogador jogador, int quantidadePalitos);
  void entrarPartida (compilacaoIDL.Jogador jogador);
  void sairPartida (compilacaoIDL.Jogador jogador);
} // interface AcoesJogadorOperations
