package compilacaoIDL;


/**
* compilacaoIDL/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Thursday, June 22, 2017 10:32:59 AM GMT-03:00
*/

public interface ClienteOperations 
{
  void sentar (String nome, int lugar);
  void escreverMensagem (String mensagem);
  void apostar (int lugar);
  void palpite (int lugar, int palpite);
  void reiniciarRodada (int lugar, int quantidadePalitosRestantes);
  void sairSala (int lugar);
} // interface ClienteOperations
