package compilacaoIDL;

/**
* compilacaoIDL/ClienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Wednesday, June 21, 2017 9:46:39 PM GMT-03:00
*/

public final class ClienteHolder implements org.omg.CORBA.portable.Streamable
{
  public compilacaoIDL.Cliente value = null;

  public ClienteHolder ()
  {
  }

  public ClienteHolder (compilacaoIDL.Cliente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = compilacaoIDL.ClienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    compilacaoIDL.ClienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return compilacaoIDL.ClienteHelper.type ();
  }

}
