package compilacaoIDL;


/**
* compilacaoIDL/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Wednesday, June 21, 2017 9:04:23 PM GMT-03:00
*/

public interface ClienteOperations 
{
  void sentar (String nome, int lugar);
  void escreverMensagem (String mensagem);
  void apostar (int lugar);
  void palpite (int lugar, int palpite);
  void vencedorRodada (String nome);
  void empateRodada ();
  void sairSala (int lugar);
} // interface ClienteOperations
