package compilacaoIDL;


/**
* compilacaoIDL/ClienteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Wednesday, June 21, 2017 9:46:39 PM GMT-03:00
*/

abstract public class ClienteHelper
{
  private static String  _id = "IDL:compilacaoIDL/Cliente:1.0";

  public static void insert (org.omg.CORBA.Any a, compilacaoIDL.Cliente that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static compilacaoIDL.Cliente extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (compilacaoIDL.ClienteHelper.id (), "Cliente");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static compilacaoIDL.Cliente read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClienteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, compilacaoIDL.Cliente value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static compilacaoIDL.Cliente narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof compilacaoIDL.Cliente)
      return (compilacaoIDL.Cliente)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      compilacaoIDL._ClienteStub stub = new compilacaoIDL._ClienteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static compilacaoIDL.Cliente unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof compilacaoIDL.Cliente)
      return (compilacaoIDL.Cliente)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      compilacaoIDL._ClienteStub stub = new compilacaoIDL._ClienteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
