package compilacaoIDL;


/**
* compilacaoIDL/EventosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Thursday, June 15, 2017 6:49:05 PM GMT-03:00
*/

public interface EventosOperations 
{
  void sentar (int lugar);
  void enviarMensagem (String mensagem);
  void esolherQuantidadePalitos (compilacaoIDL.Jogador jogador, int quantidadePalitos);
  void apostar (compilacaoIDL.Jogador jogador, int quantidadePalitos);
  void entrarPartida (compilacaoIDL.Jogador jogador);
  void sair (int lugar);
} // interface EventosOperations
