package compilacaoIDL;


/**
* compilacaoIDL/Eventos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Monday, June 19, 2017 1:18:27 PM GMT-03:00
*/

public interface Eventos extends EventosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Eventos
