package compilacaoIDL;


/**
* compilacaoIDL/EventosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Monday, June 19, 2017 8:52:01 PM GMT-03:00
*/

public interface EventosOperations 
{
  void sentar (int lugar);
  void enviarMensagem (String mensagem);
  void esolherQuantidadePalitos (int quantidadePalitos);
  void apostar (int lugar);
  void entrarSala ();
  void sairSala (int lugar);
} // interface EventosOperations
