package compilacaoIDL;


/**
* compilacaoIDL/Jogador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Thursday, June 15, 2017 6:49:05 PM GMT-03:00
*/

public final class Jogador implements org.omg.CORBA.portable.IDLEntity
{
  public String nome = null;
  public int lugar = (int)0;
  public int totalPalitos = (int)0;
  public int quantidadePalitosApostados = (int)0;

  public Jogador ()
  {
  } // ctor

  public Jogador (String _nome, int _lugar, int _totalPalitos, int _quantidadePalitosApostados)
  {
    nome = _nome;
    lugar = _lugar;
    totalPalitos = _totalPalitos;
    quantidadePalitosApostados = _quantidadePalitosApostados;
  } // ctor

} // class Jogador
