package compilacaoIDL;


/**
* compilacaoIDL/ServidorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Wednesday, June 14, 2017 4:58:15 PM GMT-03:00
*/

public abstract class ServidorPOA extends org.omg.PortableServer.Servant
 implements compilacaoIDL.ServidorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getJogadores", new java.lang.Integer (0));
    _methods.put ("verificarNomeJogador", new java.lang.Integer (1));
    _methods.put ("atualizarChat", new java.lang.Integer (2));
    _methods.put ("passarTurno", new java.lang.Integer (3));
    _methods.put ("vencedor", new java.lang.Integer (4));
    _methods.put ("perdedor", new java.lang.Integer (5));
    _methods.put ("adicionarJogador", new java.lang.Integer (6));
    _methods.put ("removerJogador", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // compilacaoIDL/Servidor/getJogadores
       {
         compilacaoIDL.Jogador $result[] = null;
         $result = this.getJogadores ();
         out = $rh.createReply();
         compilacaoIDL.ListaJogadoresHelper.write (out, $result);
         break;
       }

       case 1:  // compilacaoIDL/Servidor/verificarNomeJogador
       {
         String nome = in.read_string ();
         boolean $result = false;
         $result = this.verificarNomeJogador (nome);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // compilacaoIDL/Servidor/atualizarChat
       {
         compilacaoIDL.Jogador jogador = compilacaoIDL.JogadorHelper.read (in);
         String mensagem = in.read_string ();
         this.atualizarChat (jogador, mensagem);
         out = $rh.createReply();
         break;
       }

       case 3:  // compilacaoIDL/Servidor/passarTurno
       {
         compilacaoIDL.Jogador jogador = compilacaoIDL.JogadorHelper.read (in);
         this.passarTurno (jogador);
         out = $rh.createReply();
         break;
       }

       case 4:  // compilacaoIDL/Servidor/vencedor
       {
         compilacaoIDL.Jogador jogador = compilacaoIDL.JogadorHelper.read (in);
         this.vencedor (jogador);
         out = $rh.createReply();
         break;
       }

       case 5:  // compilacaoIDL/Servidor/perdedor
       {
         compilacaoIDL.Jogador jogador = compilacaoIDL.JogadorHelper.read (in);
         this.perdedor (jogador);
         out = $rh.createReply();
         break;
       }

       case 6:  // compilacaoIDL/Servidor/adicionarJogador
       {
         compilacaoIDL.Jogador jogador = compilacaoIDL.JogadorHelper.read (in);
         this.adicionarJogador (jogador);
         out = $rh.createReply();
         break;
       }

       case 7:  // compilacaoIDL/Servidor/removerJogador
       {
         compilacaoIDL.Jogador jogador = compilacaoIDL.JogadorHelper.read (in);
         this.removerJogador (jogador);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:compilacaoIDL/Servidor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Servidor _this() 
  {
    return ServidorHelper.narrow(
    super._this_object());
  }

  public Servidor _this(org.omg.CORBA.ORB orb) 
  {
    return ServidorHelper.narrow(
    super._this_object(orb));
  }


} // class ServidorPOA
