package compilacaoIDL;


/**
* compilacaoIDL/Servidor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Thursday, June 22, 2017 10:32:59 AM GMT-03:00
*/

public interface Servidor extends ServidorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Servidor
