package compilacaoIDL;


/**
* compilacaoIDL/Servidor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Porrinha.idl
* Tuesday, June 20, 2017 2:53:32 PM GMT-03:00
*/

public interface Servidor extends ServidorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Servidor
